version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@0.0.10

jobs:
    test:
      docker:
        - image: circleci/node:14.4
      steps:
        - checkout
        - run:
            name: install packages
            command: npm install
        - run:
            name: Running unit test
            command: npm test


workflows:
  build-and-deploy:
      jobs:
        - test
        - aws-ecr/build-and-push-image:
            requires: 
              - test
            account-url: AWS_ECR_ACCOUNT_URL
            repo: '${AWS_REPO}'
            tag: '${CIRCLE_SHA1}'
        - aws-ecs/deploy-service-update:
            requires:
              - aws-ecr/build-and-push-image
            family: "${AWS_SERVICE_NAME_PREFIX}"
            cluster-name: "${AWS_CLUSTER_NAME_PREFIX}-cluster"
            container-image-name-updates: "container=${AWS_CONTAINER_NAME},tag=${CIRCLE_SHA1}"